---
kind: Service
apiVersion: v1
metadata:
  name: management-node
  labels:
    app: management-node
spec:
  type: ClusterIP
  selector:
    app: management-node
  ports:
    - name: api
      port: {{ include "cluster.bindPort" .Values.management.bind | int }}
      targetPort: {{ include "cluster.bindPort" .Values.management.bind | int }}
    - name: metrics
      port: {{ include "cluster.bindPort" .Values.management.serviceBind | int }}
      targetPort: {{ include "cluster.bindPort" .Values.management.serviceBind | int }}
