{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hugr-cluster
  annotations:
    {{- if .Values.prometheus.enabled }}
    prometheus.io/scrape: "true"
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className | default "nginx" }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hugr-cluster
                port:
                  number: {{ include "cluster.bindPort" .Values.workNode.bind | int }}
{{- end }}
