upstream hugr-cluster {
    server cluster-mgmt:15000;
    server cluster-worker:15000;
}

server {
    listen 15000;

    location / {
        proxy_pass http://hugr-cluster;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
