apiVersion: v1
kind: Service
metadata:
  name: work-headless
  labels:
    app: work
spec:
  clusterIP: None
  selector:
    app: work
  ports:
    - name: api
      port: {{ include "cluster.bindPort" .Values.workNode.bind | int }}
      targetPort: {{ include "cluster.bindPort" .Values.workNode.bind | int }}
    - name: metrics
      port: {{ include "cluster.bindPort" .Values.workNode.serviceBind | int }}
      targetPort: {{ include "cluster.bindPort" .Values.workNode.serviceBind | int }}
