apiVersion: v1
kind: Service
metadata:
  name: work
  labels:
    app: work
spec:
  type: ClusterIP
  selector:
    app: work
  ports:
    - name: api
      port: {{ .Values.workNode.service.bind | trimPrefix ":" | int }}
      targetPort: {{ .Values.workNode.service.bind | trimPrefix ":" | int }}