services:
  # memcached
  memcached:
    image: memcached:latest
    container_name: memcached
    ports:
      - "11211"
    volumes:
      - ../.local/mc-cache:/data
    environment:
      MEMCACHED_MEMORY_LIMIT: 1024m
      MEMCACHED_MAX_CONNECTIONS: 10
      MEMCACHED_PORT: 11211
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "11211"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 1s

  # Redis
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379"
    volumes:
      - ../.local/redis-cache:/data
    environment:
      REDIS_PASSWORD: test
      REDIS_PORT: 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 1s

  s3:
    image: minio/minio:latest
    container_name: s3
    ports:
      - "16000:9000"
    volumes:
      - ../.local/s3/:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data

  # Hugr
  hugr:
    image: ghcr.io/hugr-lab/automigrate:latest
    container_name: hugr
    depends_on:
      redis:
        condition: service_healthy
#      memcached:
#        condition: service_healthy
    ports:
      - "15000:15000"
    volumes:
      - ../:/data
    environment:
      BIND: :15000
      DEBUG: true
      CORE_DB_PATH: /data/.local/docker.duckdb
      ALLOWED_ANONYMOUS: true
      ANONYMOUS_ROLE: 'admin'
      SECRET_KEY: 'secret'
      CACHE_TTL: 15m
      CACHE_L1_ENABLED: true
      CACHE_L1_MAX_SIZE: 10000
      CACHE_L1_CLEAN_TIME: 2m
      CACHE_L1_EVICTION_TIME: 5m
      CACHE_L2_ENABLED: true
      CACHE_L2_BACKEND: 'redis'
      CACHE_L2_ADDRESSES: 'redis:6379'
      #CACHE_L2_BACKEND='memcached'
      #CACHE_L2_ADDRESSES='memcached:11211'
      CACHE_L2_PASSWORD: 'test'