name: Build and Publish Docker Image

on:
  push:
    tags:
      - 'v*'  # Только при пуше версии, например v1.0.0

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Show tag
        run: |
          echo "Tag: ${{ github.ref_name }}"

      - name: Build and push base image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: server.dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            HUGR_VERSION=${{ github.ref_name }}
          tags: |
            ghcr.io/hugr-lab/server:${{ github.ref_name }}
            ghcr.io/hugr-lab/server:latest
            
      - name: Build and push automigrate image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: automigrate.dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            HUGR_VERSION=${{ github.ref_name }}
          tags: |
            ghcr.io/hugr-lab/automigrate:${{ github.ref_name }}
            ghcr.io/hugr-lab/automigrate:latest

      - name: Build and push management image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: management.dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            HUGR_VERSION=${{ github.ref_name }}
          tags: |
            ghcr.io/hugr-lab/management:${{ github.ref_name }}
            ghcr.io/hugr-lab/management:latest