name: Build and Publish Docker Image

on:
  push:
    tags:
      - 'v*'  # Только при пуше версии, например v1.0.0

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push base image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: linux.dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            HUGR_VERSION=${{ github.ref_name }}
          tags: |
            ghcr.io/server:${{ github.ref_name }}
            ghcr.io/server:latest
            
      - name: Build and push automigrate image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: automigrate.dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            HUGR_VERSION=${{ github.ref_name }}
          tags: |
            ghcr.io/automigrate:${{ github.ref_name }}
            ghcr.io/automigrate:latest
